// Package classify assigns each ingested HTTP request a traffic_class
// label from the Cloudflare-compatible 8-value taxonomy:
//
//	user            — real human visitor with their own browser
//	ai_user_action  — live AI browse: a human chats with an LLM and
//	                  the assistant fetches the page on their behalf
//	                  (ChatGPT-User, Claude-User, Perplexity-User, ...)
//	ai_search       — AI search-engine crawlers indexing for AI answers
//	                  (PerplexityBot, OAI-SearchBot, ...)
//	ai_training     — training-data crawlers (GPTBot, ClaudeBot, CCBot,
//	                  Bytespider, ...)
//	search_index    — classic search indexers (Googlebot, Bingbot,
//	                  Yandex, Baidu, DuckDuckBot, ...)
//	social_unfurl   — link-preview / social-card bots (Slackbot,
//	                  facebookexternalhit, Twitterbot, Embedly, ...)
//	scanner         — security/uptime/perf monitoring (Censys, Pingdom,
//	                  Lighthouse, generic Chrome from a cloud range, ...)
//	bot_other       — recognized as a bot but not in any specific bucket
//
// Phase 1 only emitted "user" or "bot". Phase 2 (this package) refines
// the latter into 7 sub-classes. Default analytics queries continue to
// filter `traffic_class = 'user'`; new MCP tools surface the rest.
//
// Classification combines three signals:
//
//   1. UA-pattern matching against a curated list (~40 entries in
//      ua_patterns.go). Authoritative if the UA matches a known marker.
//   2. IP-CIDR lookup against a refreshed-every-6h trie built from the
//      vendors' published JSONs (OpenAI, Google, Bing, AWS/GCP/Azure/CF
//      cloud ranges). Phase-2 also catches spoofers — UA = "GPTBot" on
//      a non-OpenAI IP gets classified as bot_other (or scanner) instead.
//   3. Reverse-DNS for Anthropic (which doesn't publish IP ranges).
//
// The default-deny shape is intentional: unmatched bots fall to
// bot_other rather than being dropped, so customers can still see the
// long-tail traffic. UA="" alone is no longer treated as bot — many
// legitimate clients (server-side fetches, RSS readers, federated
// services) send no UA and we'd rather classify them as bot_other than
// hide them.
package classify

// Class is one of the eight traffic-class string constants below. Stored
// as a LowCardinality(String) column in ClickHouse, so it must always
// be a value listed here — never a free-form string.
type Class = string

// The eight traffic_class values. Keep these as string consts (not iota)
// because they go directly into ClickHouse as the column value and any
// mismatch between Go and the schema would silently misclassify rows.
const (
	ClassUser          Class = "user"
	ClassAIUserAction  Class = "ai_user_action"
	ClassAISearch      Class = "ai_search"
	ClassAITraining    Class = "ai_training"
	ClassSearchIndex   Class = "search_index"
	ClassSocialUnfurl  Class = "social_unfurl"
	ClassScanner       Class = "scanner"
	ClassBotOther      Class = "bot_other"
)

// AllClasses lists every valid traffic_class value, in the order we want
// them to appear in tool schemas / docs. Used by tests to assert the
// schema enum matches the package, and by the daily schema-check
// workflow to detect drift between Go and Rails.
var AllClasses = []Class{
	ClassUser,
	ClassAIUserAction,
	ClassAISearch,
	ClassAITraining,
	ClassSearchIndex,
	ClassSocialUnfurl,
	ClassScanner,
	ClassBotOther,
}

// IsHuman returns true for traffic generated by a real human, including
// AI-mediated browsing where Claude/ChatGPT fetched the page on a user's
// behalf. Used by the "humans" MCP query alias.
func IsHuman(c Class) bool {
	return c == ClassUser || c == ClassAIUserAction
}

// IsBot returns true for everything that is not a real visitor — i.e.
// every class except "user". Note that ai_user_action is NOT considered
// a bot by this function; it's a human interaction mediated through an
// AI client. Use IsBot for the "is this automated traffic" question and
// IsHuman for the "is there a person behind this" question.
func IsBot(c Class) bool {
	return c != ClassUser && c != ClassAIUserAction
}
